// 
//  Copyright 2022 Sergey Khabarov, sergeykhbr@gmail.com
// 
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
// 
//      http://www.apache.org/licenses/LICENSE-2.0
// 
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
// 

#include "accel_soc.h"
#include "../../../prj/impl/asic/target_cfg.h"

accel_soc::accel_soc(GenObject *parent, const char *name, const char *comment) :
    ModuleObject(parent, "accel_soc", name, comment),
    // simulation parameters
    sim_uart_speedup_rate(this, "sim_uart_speedup_rate", "0", "simulation UART speed-up: 0=no speed up, 1=2x, 2=4x, etc"),
    // Generic parameters
    // Ports
    i_sys_nrst(this, "i_sys_nrst", "1", "Power-on system reset active LOW"),
    i_sys_clk(this, "i_sys_clk", "1", "System/Bus clock"),
    i_dbg_nrst(this, "i_dbg_nrst", "1", "Reset from Debug interface (DMI). Reset everything except DMI"),
    i_ddr_nrst(this, "i_ddr_nrst", "1", "DDR related logic reset (AXI clock transformator)"),
    i_ddr_clk(this, "i_ddr_clk", "1", "DDR memoru clock"),
    _gpio0_(this, "GPIO signals:"),
    i_gpio(this, "i_gpio", "12"),
    o_gpio(this, "o_gpio", "12"),
    o_gpio_dir(this, "o_gpio_dir", "12"),
    _jtag0_(this, "JTAG signals:"),
    i_jtag_trst(this, "i_jtag_trst", "1"),
    i_jtag_tck(this, "i_jtag_tck", "1"),
    i_jtag_tms(this, "i_jtag_tms", "1"),
    i_jtag_tdi(this, "i_jtag_tdi", "1"),
    o_jtag_tdo(this, "o_jtag_tdo", "1"),
    o_jtag_vref(this, "o_jtag_vref", "1"),
    _uart1_(this, "UART1 signals"),
    i_uart1_rd(this, "i_uart1_rd", "1"),
    o_uart1_td(this, "o_uart1_td", "1"),
#if GENCFG_SD_CTRL_ENABLE
    _sdctrl0_(this, "SD-card signals:"),
    o_sd_sclk(this, "o_sd_sclk", "1", "Clock up to 50 MHz"),
    i_sd_cmd(this, "i_sd_cmd", "1", "Command response;"),
    o_sd_cmd(this, "o_sd_cmd", "1", "Command request; DO in SPI mode"),
    o_sd_cmd_dir(this, "o_sd_cmd_dir", "1", "Direction bit: 1=input; 0=output"),
    i_sd_dat0(this, "i_sd_dat0", "1", "Data Line[0] input; DI in SPI mode"),
    o_sd_dat0(this, "o_sd_dat0", "1", "Data Line[0] output"),
    o_sd_dat0_dir(this, "o_sd_dat0_dir", "1", "Direction bit: 1=input; 0=output"),
    i_sd_dat1(this, "i_sd_dat1", "1", "Data Line[1] input"),
    o_sd_dat1(this, "o_sd_dat1", "1", "Data Line[1] output"),
    o_sd_dat1_dir(this, "o_sd_dat1_dir", "1", "Direction bit: 1=input; 0=output"),
    i_sd_dat2(this, "i_sd_dat2", "1", "Data Line[2] input"),
    o_sd_dat2(this, "o_sd_dat2", "1", "Data Line[2] output"),
    o_sd_dat2_dir(this, "o_sd_dat2_dir", "1", "Direction bit: 1=input; 0=output"),
    i_sd_cd_dat3(this, "i_sd_cd_dat3", "1", "Card Detect / Data Line[3] input"),
    o_sd_cd_dat3(this, "o_sd_cd_dat3", "1", "Card Detect / Data Line[3] output; CS output in SPI mode"),
    o_sd_cd_dat3_dir(this, "o_sd_cd_dat3_dir", "1", "Direction bit: 1=input; 0=output"),
    i_sd_detected(this, "i_sd_detected", "1", "SD-card detected"),
    i_sd_protect(this, "i_sd_protect", "1", "SD-card write protect"),
#endif
    _prci0_(this, "PLL and Reset interfaces:"),
    o_dmreset(this, "o_dmreset", "1", "Debug reset request. Everything except DMI."),
    o_prci_pmapinfo(this, "o_prci_pmapinfo", "PRCI mapping information"),
    i_prci_pdevcfg(this, "i_prci_pdevcfg", "PRCI device descriptor"),
    o_prci_apbi(this, "o_prci_apbi", "APB: PLL and Reset configuration interface"),
    i_prci_apbo(this, "i_prci_apbo", "APB: PLL and Reset configuration interface"),
    _ddr0_(this, "DDR interfaces:"),
    o_ddr_pmapinfo(this, "o_ddr_pmapinfo", "DDR configuration mapping information"),
    i_ddr_pdevcfg(this, "i_ddr_pdevcfg", "DDR configuration device descriptor"),
    o_ddr_apbi(this, "o_ddr_apbi", "APB: DDR configuration interface"),
    i_ddr_apbo(this, "i_ddr_apbo", "APB: DDR configuration interface"),
    o_ddr_xmapinfo(this, "o_ddr_xmapinfo", "DDR memory bank mapping information"),
    i_ddr_xdevcfg(this, "i_ddr_xdevcfg", "DDR memory bank descriptor"),
    o_ddr_xslvi(this, "o_ddr_xslvi", "AXI DDR memory interface"),
    i_ddr_xslvo(this, "i_ddr_xslvo", "AXI DDR memory interface"),
#if GENCFG_PCIE_ENABLE
    _pcie0_(this, "PCIE endpoint interface:"),
    i_pcie_clk(this, "i_pcie_clk", "1", "PCIE clock generated by end-point"),
    i_pcie_nrst(this, "i_pcie_nrst", "1", "PCIE reset active LOW generated inside of PRCI"),
    i_pcie_completer_id(this, "i_pcie_completer_id", "16", "Bus, Device, Function"),
    o_pcie_dmao(this, "o_pcie_dmao", "PCIE DMA enging interface"),
    i_pcie_dmai(this, "i_pcie_dmai", "PCIE DMA enging interface"),
#endif
    // param
    _hwid0_(this),
    _hwid1_(this, "Hardware SoC Identificator."),
    _hwid2_(this, "Read Only unique platform identificator that could be read by FW"),
    SOC_HW_ID(this, "SOC_HW_ID", "32", GENCFG_SOC_HW_ID, NO_COMMENT),
    _cfg0_(this),
    _cfg1_(this, "UARTx fifo log2(size) in bytes:"),
    SOC_UART1_LOG2_FIFOSZ(this, "SOC_UART1_LOG2_FIFOSZ", "4"),
    _cfg2_(this),
    _cfg3_(this, "Number of available generic IO pins:"),
    SOC_GPIO0_WIDTH(this, "SOC_GPIO0_WIDTH", "12"),
#if GENCFG_SD_CTRL_ENABLE
    _cfg4_(this),
    _cfg5_(this, "SD-card in SPI mode buffer size. It should be at least log2(512) Bytes:"),
    SOC_SPI0_LOG2_FIFOSZ(this, "SOC_SPI0_LOG2_FIFOSZ", "9"),
#endif
    _plic0_(this),
    _plic1_(this, "Number of contexts in PLIC controller."),
    _plic2_(this, "Example FU740: S7 Core0 (M) + 4xU74 Cores (M+S)."),
    SOC_PLIC_CONTEXT_TOTAL(this, "SOC_PLIC_CONTEXT_TOTAL", "9"),
    _plic3_(this, "Any number up to 1024. Zero interrupt must be 0."),
    SOC_PLIC_IRQ_TOTAL(this, "SOC_PLIC_IRQ_TOTAL", "73"),
    // Singals:
    acpo(this, "acpo", NO_COMMENT),
    acpi(this, "acpi", NO_COMMENT),
    bus0_mapinfo(this, "bus0_mapinfo"),
    aximi(this, "aximi"),
    aximo(this, "aximo"),
    axisi(this, "axisi"),
    axiso(this, "axiso"),
    bus1_mapinfo(this, "bus1_mapinfo"),
    apbi(this, "apbi"),
    apbo(this, "apbo"),
    dev_pnp(this, "dev_pnp", NO_COMMENT),
    wb_clint_mtimer(this, "wb_clint_mtimer", "64"),
    wb_clint_msip(this, "wb_clint_msip", "CFG_CPU_MAX"),
    wb_clint_mtip(this, "wb_clint_mtip", "CFG_CPU_MAX"),
    wb_plic_xeip(this, "wb_plic_xeip", "SOC_PLIC_CONTEXT_TOTAL"),
    wb_plic_meip(this, "wb_plic_meip", "CFG_CPU_MAX"),
    wb_plic_seip(this, "wb_plic_seip", "CFG_CPU_MAX"),
    w_irq_uart1(this, "w_irq_uart1", "1"),
    wb_irq_gpio(this, "wb_irq_gpio", "SOC_GPIO0_WIDTH"),
    w_irq_pnp(this, "w_irq_pnp", "1"),
    wb_ext_irqs(this, "wb_ext_irqs", "SOC_PLIC_IRQ_TOTAL"),
#if GENCFG_PCIE_ENABLE
    wb_pcie_dma_state(this, "wb_pcie_dma_state", "4"),
    wb_dbg_pcie_dmai(this, "wb_dbg_pcie_dmai", NO_COMMENT),
#endif
    // submodules:
    bus0(this, "bus0"),
    bus1(this, "bus1"),
    rom0(this, "rom0"),
    sram0(this, "sram0"),
    clint0(this, "clint0"),
    plic0(this, "plic0"),
    uart1(this, "uart1"),
    gpio0(this, "gpio0"),
#if GENCFG_SD_CTRL_ENABLE
    sdctrl0(this, "sdctrl0"),
#endif
#if GENCFG_PCIE_ENABLE
    pcidma0(this, "pcidma0"),
    ppcie0(this, "ppcie0", NO_COMMENT),
#endif
    pnp0(this, "pnp0"),
    group0(this, "group0"),
    u_cdc_ddr0(this, "u_cdc_ddr0"),
    comb(this)
{
    Operation::start(this);

    // Create and connet Sub-modules:
    NEW(bus0, bus0.getName().c_str());
        CONNECT(bus0, 0, bus0.i_clk, i_sys_clk);
        CONNECT(bus0, 0, bus0.i_nrst, i_sys_nrst);
        CONNECT(bus0, 0, bus0.o_cfg, ARRITEM(dev_pnp, glob_pnp_cfg_->SOC_PNP_XCTRL0, dev_pnp));
        CONNECT(bus0, 0, bus0.i_xmsto, aximo);
        CONNECT(bus0, 0, bus0.o_xmsti, aximi);
        CONNECT(bus0, 0, bus0.i_xslvo, axiso);
        CONNECT(bus0, 0, bus0.o_xslvi, axisi);
        CONNECT(bus0, 0, bus0.o_mapinfo, bus0_mapinfo);
    ENDNEW();

TEXT();
    NEW(bus1, bus1.getName().c_str());
        CONNECT(bus1, 0, bus1.i_clk, i_sys_clk);
        CONNECT(bus1, 0, bus1.i_nrst, i_sys_nrst);
        CONNECT(bus1, 0, bus1.i_mapinfo, ARRITEM(bus0_mapinfo, glob_bus0_cfg_->CFG_BUS0_XSLV_PBRIDGE, bus0_mapinfo));
        CONNECT(bus1, 0, bus1.o_cfg, ARRITEM(dev_pnp, glob_pnp_cfg_->SOC_PNP_PBRIDGE0, dev_pnp));
        CONNECT(bus1, 0, bus1.i_xslvi, ARRITEM(axisi, glob_bus0_cfg_->CFG_BUS0_XSLV_PBRIDGE, axisi));
        CONNECT(bus1, 0, bus1.o_xslvo, ARRITEM(axiso, glob_bus0_cfg_->CFG_BUS0_XSLV_PBRIDGE, axiso));
        CONNECT(bus1, 0, bus1.i_apbo, apbo);
        CONNECT(bus1, 0, bus1.o_apbi, apbi);
        CONNECT(bus1, 0, bus1.o_mapinfo, bus1_mapinfo);
    ENDNEW();

TEXT();
    group0.cpu_num.setObjValue(SCV_get_cfg_type(this, "CFG_CPU_NUM"));
    group0.l2cache_ena.setObjValue(SCV_get_cfg_type(this, "CFG_L2CACHE_ENA"));
    NEW(group0, group0.getName().c_str());
        CONNECT(group0, 0, group0.i_clk, i_sys_clk);
        CONNECT(group0, 0, group0.i_cores_nrst, i_sys_nrst);
        CONNECT(group0, 0, group0.i_dmi_nrst, i_dbg_nrst);
        CONNECT(group0, 0, group0.i_trst, i_jtag_trst);
        CONNECT(group0, 0, group0.i_tck, i_jtag_tck);
        CONNECT(group0, 0, group0.i_tms, i_jtag_tms);
        CONNECT(group0, 0, group0.i_tdi, i_jtag_tdi);
        CONNECT(group0, 0, group0.o_tdo, o_jtag_tdo);
        CONNECT(group0, 0, group0.i_msip, wb_clint_msip);
        CONNECT(group0, 0, group0.i_mtip, wb_clint_mtip);
        CONNECT(group0, 0, group0.i_meip, wb_plic_meip);
        CONNECT(group0, 0, group0.i_seip, wb_plic_seip);
        CONNECT(group0, 0, group0.i_mtimer, wb_clint_mtimer);
        CONNECT(group0, 0, group0.i_acpo, acpo);
        CONNECT(group0, 0, group0.o_acpi, acpi);
        CONNECT(group0, 0, group0.o_xmst_cfg, ARRITEM(dev_pnp, glob_pnp_cfg_->SOC_PNP_GROUP0, dev_pnp));
        CONNECT(group0, 0, group0.i_msti, ARRITEM(aximi, glob_bus0_cfg_->CFG_BUS0_XMST_GROUP0, aximi));
        CONNECT(group0, 0, group0.o_msto, ARRITEM(aximo, glob_bus0_cfg_->CFG_BUS0_XMST_GROUP0, aximo));
        CONNECT(group0, 0, group0.i_dmi_mapinfo, ARRITEM(bus1_mapinfo, glob_bus1_cfg_->CFG_BUS1_PSLV_DMI, bus1_mapinfo));
        CONNECT(group0, 0, group0.o_dmi_cfg, ARRITEM(dev_pnp, glob_pnp_cfg_->SOC_PNP_DMI, dev_pnp));
        CONNECT(group0, 0, group0.i_dmi_apbi, ARRITEM(apbi, glob_bus1_cfg_->CFG_BUS1_PSLV_DMI, apbi));
        CONNECT(group0, 0, group0.o_dmi_apbo, ARRITEM(apbo, glob_bus1_cfg_->CFG_BUS1_PSLV_DMI, apbo));
        CONNECT(group0, 0, group0.o_dmreset, o_dmreset);
    ENDNEW();

TEXT();
    rom0.abits.setObjValue(SCV_get_cfg_type(this, "CFG_BOOTROM_LOG2_SIZE"));
    rom0.filename.setObjValue(SCV_get_cfg_type(this, "CFG_BOOTROM_FILE_HEX"));
    NEW(rom0, rom0.getName().c_str());
        CONNECT(rom0, 0, rom0.i_clk, i_sys_clk);
        CONNECT(rom0, 0, rom0.i_nrst, i_sys_nrst);
        CONNECT(rom0, 0, rom0.i_mapinfo, ARRITEM(bus0_mapinfo, glob_bus0_cfg_->CFG_BUS0_XSLV_BOOTROM, bus0_mapinfo));
        CONNECT(rom0, 0, rom0.o_cfg, ARRITEM(dev_pnp, glob_pnp_cfg_->SOC_PNP_BOOTROM, dev_pnp));
        CONNECT(rom0, 0, rom0.i_xslvi, ARRITEM(axisi, glob_bus0_cfg_->CFG_BUS0_XSLV_BOOTROM, axisi));
        CONNECT(rom0, 0, rom0.o_xslvo, ARRITEM(axiso, glob_bus0_cfg_->CFG_BUS0_XSLV_BOOTROM, axiso));
    ENDNEW();

TEXT();
    sram0.abits.setObjValue(SCV_get_cfg_type(this, "CFG_SRAM_LOG2_SIZE"));
    NEW(sram0, sram0.getName().c_str());
        CONNECT(sram0, 0, sram0.i_clk, i_sys_clk);
        CONNECT(sram0, 0, sram0.i_nrst, i_sys_nrst);
        CONNECT(sram0, 0, sram0.i_mapinfo, ARRITEM(bus0_mapinfo, glob_bus0_cfg_->CFG_BUS0_XSLV_SRAM, bus0_mapinfo));
        CONNECT(sram0, 0, sram0.o_cfg, ARRITEM(dev_pnp, glob_pnp_cfg_->SOC_PNP_SRAM, dev_pnp));
        CONNECT(sram0, 0, sram0.i_xslvi, ARRITEM(axisi, glob_bus0_cfg_->CFG_BUS0_XSLV_SRAM, axisi));
        CONNECT(sram0, 0, sram0.o_xslvo, ARRITEM(axiso, glob_bus0_cfg_->CFG_BUS0_XSLV_SRAM, axiso));
    ENDNEW();

TEXT();
    plic0.ctxmax.setObjValue(&SOC_PLIC_CONTEXT_TOTAL);
    clint0.cpu_total.setObjValue(SCV_get_cfg_type(this, "CFG_CPU_MAX"));
    NEW(clint0, clint0.getName().c_str());
        CONNECT(clint0, 0, clint0.i_clk, i_sys_clk);
        CONNECT(clint0, 0, clint0.i_nrst, i_sys_nrst);
        CONNECT(clint0, 0, clint0.i_mapinfo, ARRITEM(bus0_mapinfo, glob_bus0_cfg_->CFG_BUS0_XSLV_CLINT, bus0_mapinfo));
        CONNECT(clint0, 0, clint0.o_cfg, ARRITEM(dev_pnp, glob_pnp_cfg_->SOC_PNP_CLINT, dev_pnp));
        CONNECT(clint0, 0, clint0.i_xslvi, ARRITEM(axisi, glob_bus0_cfg_->CFG_BUS0_XSLV_CLINT, axisi));
        CONNECT(clint0, 0, clint0.o_xslvo, ARRITEM(axiso, glob_bus0_cfg_->CFG_BUS0_XSLV_CLINT, axiso));
        CONNECT(clint0, 0, clint0.o_mtimer, wb_clint_mtimer);
        CONNECT(clint0, 0, clint0.o_msip, wb_clint_msip);
        CONNECT(clint0, 0, clint0.o_mtip, wb_clint_mtip);
    ENDNEW();

TEXT();
    plic0.irqmax.setObjValue(&SOC_PLIC_IRQ_TOTAL);
    NEW(plic0, plic0.getName().c_str());
        CONNECT(plic0, 0, plic0.i_clk, i_sys_clk);
        CONNECT(plic0, 0, plic0.i_nrst, i_sys_nrst);
        CONNECT(plic0, 0, plic0.i_mapinfo, ARRITEM(bus0_mapinfo, glob_bus0_cfg_->CFG_BUS0_XSLV_PLIC, bus0_mapinfo));
        CONNECT(plic0, 0, plic0.o_cfg, ARRITEM(dev_pnp, glob_pnp_cfg_->SOC_PNP_PLIC, dev_pnp));
        CONNECT(plic0, 0, plic0.i_xslvi, ARRITEM(axisi, glob_bus0_cfg_->CFG_BUS0_XSLV_PLIC, axisi));
        CONNECT(plic0, 0, plic0.o_xslvo, ARRITEM(axiso, glob_bus0_cfg_->CFG_BUS0_XSLV_PLIC, axiso));
        CONNECT(plic0, 0, plic0.i_irq_request, wb_ext_irqs);
        CONNECT(plic0, 0, plic0.o_ip, wb_plic_xeip);
    ENDNEW();

TEXT();
    NEW(u_cdc_ddr0, u_cdc_ddr0.getName().c_str());
        CONNECT(u_cdc_ddr0, 0, u_cdc_ddr0.i_xslv_clk, i_sys_clk);
        CONNECT(u_cdc_ddr0, 0, u_cdc_ddr0.i_xslv_nrst, i_sys_nrst);
        CONNECT(u_cdc_ddr0, 0, u_cdc_ddr0.i_xslvi, ARRITEM(axisi, glob_bus0_cfg_->CFG_BUS0_XSLV_DDR, axisi));
        CONNECT(u_cdc_ddr0, 0, u_cdc_ddr0.o_xslvo, ARRITEM(axiso, glob_bus0_cfg_->CFG_BUS0_XSLV_DDR, axiso));
        CONNECT(u_cdc_ddr0, 0, u_cdc_ddr0.i_xmst_clk, i_ddr_clk);
        CONNECT(u_cdc_ddr0, 0, u_cdc_ddr0.i_xmst_nrst, i_ddr_nrst);
        CONNECT(u_cdc_ddr0, 0, u_cdc_ddr0.o_xmsto, o_ddr_xslvi);
        CONNECT(u_cdc_ddr0, 0, u_cdc_ddr0.i_xmsti, i_ddr_xslvo);
    ENDNEW();

TEXT();
    uart1.log2_fifosz.setObjValue(&SOC_UART1_LOG2_FIFOSZ);
    uart1.sim_speedup_rate.setObjValue(&sim_uart_speedup_rate);
    NEW(uart1, uart1.getName().c_str());
        CONNECT(uart1, 0, uart1.i_clk, i_sys_clk);
        CONNECT(uart1, 0, uart1.i_nrst, i_sys_nrst);
        CONNECT(uart1, 0, uart1.i_mapinfo, ARRITEM(bus1_mapinfo, glob_bus1_cfg_->CFG_BUS1_PSLV_UART1, bus1_mapinfo));
        CONNECT(uart1, 0, uart1.o_cfg, ARRITEM(dev_pnp, glob_pnp_cfg_->SOC_PNP_UART1, dev_pnp));
        CONNECT(uart1, 0, uart1.i_apbi, ARRITEM(apbi, glob_bus1_cfg_->CFG_BUS1_PSLV_UART1, apbi));
        CONNECT(uart1, 0, uart1.o_apbo, ARRITEM(apbo, glob_bus1_cfg_->CFG_BUS1_PSLV_UART1, apbo));
        CONNECT(uart1, 0, uart1.i_rd, i_uart1_rd);
        CONNECT(uart1, 0, uart1.o_td, o_uart1_td);
        CONNECT(uart1, 0, uart1.o_irq, w_irq_uart1);
    ENDNEW();

TEXT();
    gpio0.width.setObjValue(&SOC_GPIO0_WIDTH);
    NEW(gpio0, gpio0.getName().c_str());
        CONNECT(gpio0, 0, gpio0.i_clk, i_sys_clk);
        CONNECT(gpio0, 0, gpio0.i_nrst, i_sys_nrst);
        CONNECT(gpio0, 0, gpio0.i_mapinfo, ARRITEM(bus1_mapinfo, glob_bus1_cfg_->CFG_BUS1_PSLV_GPIO, bus1_mapinfo));
        CONNECT(gpio0, 0, gpio0.o_cfg, ARRITEM(dev_pnp, glob_pnp_cfg_->SOC_PNP_GPIO, dev_pnp));
        CONNECT(gpio0, 0, gpio0.i_apbi, ARRITEM(apbi, glob_bus1_cfg_->CFG_BUS1_PSLV_GPIO, apbi));
        CONNECT(gpio0, 0, gpio0.o_apbo, ARRITEM(apbo, glob_bus1_cfg_->CFG_BUS1_PSLV_GPIO, apbo));
        CONNECT(gpio0, 0, gpio0.i_gpio, i_gpio);
        CONNECT(gpio0, 0, gpio0.o_gpio_dir, o_gpio_dir);
        CONNECT(gpio0, 0, gpio0.o_gpio, o_gpio);
        CONNECT(gpio0, 0, gpio0.o_irq, wb_irq_gpio);
    ENDNEW();

#if GENCFG_SD_CTRL_ENABLE
TEXT();
    NEW(sdctrl0, sdctrl0.getName().c_str());
        CONNECT(sdctrl0, 0, sdctrl0.i_clk, i_sys_clk);
        CONNECT(sdctrl0, 0, sdctrl0.i_nrst, i_sys_nrst);
        CONNECT(sdctrl0, 0, sdctrl0.i_xmapinfo, ARRITEM(bus0_mapinfo, glob_bus0_cfg_->CFG_BUS0_XSLV_SDCTRL_MEM, bus0_mapinfo));
        CONNECT(sdctrl0, 0, sdctrl0.o_xcfg, ARRITEM(dev_pnp, glob_pnp_cfg_->SOC_PNP_SDCTRL_MEM, dev_pnp));
        CONNECT(sdctrl0, 0, sdctrl0.i_xslvi, ARRITEM(axisi, glob_bus0_cfg_->CFG_BUS0_XSLV_SDCTRL_MEM, axisi));
        CONNECT(sdctrl0, 0, sdctrl0.o_xslvo, ARRITEM(axiso, glob_bus0_cfg_->CFG_BUS0_XSLV_SDCTRL_MEM, axiso));
        CONNECT(sdctrl0, 0, sdctrl0.i_pmapinfo, ARRITEM(bus1_mapinfo, glob_bus1_cfg_->CFG_BUS1_PSLV_SDCTRL_REG, bus1_mapinfo));
        CONNECT(sdctrl0, 0, sdctrl0.o_pcfg, ARRITEM(dev_pnp, glob_pnp_cfg_->SOC_PNP_SDCTRL_REG, dev_pnp));
        CONNECT(sdctrl0, 0, sdctrl0.i_apbi, ARRITEM(apbi, glob_bus1_cfg_->CFG_BUS1_PSLV_SDCTRL_REG, apbi));
        CONNECT(sdctrl0, 0, sdctrl0.o_apbo, ARRITEM(apbo, glob_bus1_cfg_->CFG_BUS1_PSLV_SDCTRL_REG, apbo));
        CONNECT(sdctrl0, 0, sdctrl0.o_sclk, o_sd_sclk);
        CONNECT(sdctrl0, 0, sdctrl0.i_cmd, i_sd_cmd);
        CONNECT(sdctrl0, 0, sdctrl0.o_cmd, o_sd_cmd);
        CONNECT(sdctrl0, 0, sdctrl0.o_cmd_dir, o_sd_cmd_dir);
        CONNECT(sdctrl0, 0, sdctrl0.i_dat0, i_sd_dat0);
        CONNECT(sdctrl0, 0, sdctrl0.o_dat0, o_sd_dat0);
        CONNECT(sdctrl0, 0, sdctrl0.o_dat0_dir, o_sd_dat0_dir);
        CONNECT(sdctrl0, 0, sdctrl0.i_dat1, i_sd_dat1);
        CONNECT(sdctrl0, 0, sdctrl0.o_dat1, o_sd_dat1);
        CONNECT(sdctrl0, 0, sdctrl0.o_dat1_dir, o_sd_dat1_dir);
        CONNECT(sdctrl0, 0, sdctrl0.i_dat2, i_sd_dat2);
        CONNECT(sdctrl0, 0, sdctrl0.o_dat2, o_sd_dat2);
        CONNECT(sdctrl0, 0, sdctrl0.o_dat2_dir, o_sd_dat2_dir);
        CONNECT(sdctrl0, 0, sdctrl0.i_cd_dat3, i_sd_cd_dat3);
        CONNECT(sdctrl0, 0, sdctrl0.o_cd_dat3, o_sd_cd_dat3);
        CONNECT(sdctrl0, 0, sdctrl0.o_cd_dat3_dir, o_sd_cd_dat3_dir);
        CONNECT(sdctrl0, 0, sdctrl0.i_detected, i_sd_detected);
        CONNECT(sdctrl0, 0, sdctrl0.i_protect, i_sd_protect);
    ENDNEW();
#endif

#if GENCFG_PCIE_ENABLE
TEXT();
    TEXT("See reference: pg054-7series-pcie.pdf");
    NEW(pcidma0, pcidma0.getName().c_str());
        CONNECT(pcidma0, 0, pcidma0.i_nrst, i_pcie_nrst);
        CONNECT(pcidma0, 0, pcidma0.i_clk, i_sys_clk);
        CONNECT(pcidma0, 0, pcidma0.i_pcie_phy_clk, i_pcie_clk);
        CONNECT(pcidma0, 0, pcidma0.i_pcie_dmai, i_pcie_dmai);
        CONNECT(pcidma0, 0, pcidma0.o_pcie_dmao, o_pcie_dmao);
        CONNECT(pcidma0, 0, pcidma0.i_pcie_completer_id, i_pcie_completer_id);
        CONNECT(pcidma0, 0, pcidma0.o_xmst_cfg, ARRITEM(dev_pnp, glob_pnp_cfg_->SOC_PNP_PCIE_DMA, dev_pnp));
        CONNECT(pcidma0, 0, pcidma0.i_xmsti, ARRITEM(aximi, glob_bus0_cfg_->CFG_BUS0_XMST_PCIE, aximi));
        CONNECT(pcidma0, 0, pcidma0.o_xmsto, ARRITEM(aximo, glob_bus0_cfg_->CFG_BUS0_XMST_PCIE, aximo));
        CONNECT(pcidma0, 0, pcidma0.o_dma_state, wb_pcie_dma_state);
        CONNECT(pcidma0, 0, pcidma0.o_dbg_pcie_dmai, wb_dbg_pcie_dmai);
    ENDNEW();

TEXT();
    NEW(ppcie0, ppcie0.getName().c_str());
        CONNECT(ppcie0, 0, ppcie0.i_clk, i_sys_clk);
        CONNECT(ppcie0, 0, ppcie0.i_nrst, i_sys_nrst);
        CONNECT(ppcie0, 0, ppcie0.i_mapinfo, ARRITEM(bus1_mapinfo, glob_bus1_cfg_->CFG_BUS1_PSLV_PCIE, bus1_mapinfo));
        CONNECT(ppcie0, 0, ppcie0.o_cfg, ARRITEM(dev_pnp, glob_pnp_cfg_->SOC_PNP_PCIE_APB, dev_pnp));
        CONNECT(ppcie0, 0, ppcie0.i_apbi, ARRITEM(apbi, glob_bus1_cfg_->CFG_BUS1_PSLV_PCIE, apbi));
        CONNECT(ppcie0, 0, ppcie0.o_apbo, ARRITEM(apbo, glob_bus1_cfg_->CFG_BUS1_PSLV_PCIE, apbo));
        CONNECT(ppcie0, 0, ppcie0.i_pcie_completer_id, i_pcie_completer_id);
        CONNECT(ppcie0, 0, ppcie0.i_dma_state, wb_pcie_dma_state);
        CONNECT(ppcie0, 0, ppcie0.i_dbg_pcie_dmai, wb_dbg_pcie_dmai);
    ENDNEW();
#endif  // GENCFG_PCIE_ENABLE

TEXT();
    pnp0.cfg_slots.setObjValue(SCV_get_cfg_type(this, "SOC_PNP_TOTAL"));
    pnp0.hw_id.setObjValue(&SOC_HW_ID);
    pnp0.cpu_max.setObjValue(SCV_get_cfg_type(this, "CFG_CPU_NUM"));
    pnp0.l2cache_ena.setObjValue(SCV_get_cfg_type(this, "CFG_L2CACHE_ENA"));
    pnp0.plic_irq_max.setObjValue(&SOC_PLIC_IRQ_TOTAL);
    NEW(pnp0, pnp0.getName().c_str());
        CONNECT(pnp0, 0, pnp0.i_clk, i_sys_clk);
        CONNECT(pnp0, 0, pnp0.i_nrst, i_sys_nrst);
        CONNECT(pnp0, 0, pnp0.i_mapinfo, ARRITEM(bus1_mapinfo, glob_bus1_cfg_->CFG_BUS1_PSLV_PNP, bus1_mapinfo));
        CONNECT(pnp0, 0, pnp0.i_cfg, dev_pnp);
        CONNECT(pnp0, 0, pnp0.o_cfg, ARRITEM(dev_pnp, glob_pnp_cfg_->SOC_PNP_PNP, dev_pnp));
        CONNECT(pnp0, 0, pnp0.i_apbi, ARRITEM(apbi, glob_bus1_cfg_->CFG_BUS1_PSLV_PNP, apbi));
        CONNECT(pnp0, 0, pnp0.o_apbo, ARRITEM(apbo, glob_bus1_cfg_->CFG_BUS1_PSLV_PNP, apbo));
        CONNECT(pnp0, 0, pnp0.o_irq, w_irq_pnp);
    ENDNEW();

    Operation::start(&comb);
    proc_comb();
}

void accel_soc::proc_comb() {
    river_cfg *cfg = glob_river_cfg_;
    types_amba *amba = glob_types_amba_;


    TEXT();
    TEXT("assign interrupts:");
    SETBITS(comb.vb_ext_irqs, 22, 0, ALLZEROS());
    SETBITS(comb.vb_ext_irqs, DEC(ADD2(CONST("23"), SOC_GPIO0_WIDTH)),
                              CONST("23"),
                              wb_irq_gpio, "FU740: 16 bits, current 12-bits");
    SETBIT(comb.vb_ext_irqs, 39, w_irq_uart1);
    SETBITS(comb.vb_ext_irqs, 69, 40, ALLZEROS());
    SETBIT(comb.vb_ext_irqs, 70, w_irq_pnp);
    SETBITS(comb.vb_ext_irqs, DEC(SOC_PLIC_IRQ_TOTAL), CONST("71"), ALLZEROS());
    SETVAL(wb_ext_irqs, comb.vb_ext_irqs);

    TEXT();
    TEXT("FU740 implements 5 cores (we implement only 4):");
    TEXT("    Hart0 - M-mode only (S7 Core RV64IMAC)");
    TEXT("    Hart1..4 - M+S modes (U74 Cores RV64GC)");
    TEXT("Hart4 ignored");
    SETVAL(wb_plic_meip, CCx(4, &BIT(wb_plic_xeip, 5),
                                &BIT(wb_plic_xeip, 3),
                                &BIT(wb_plic_xeip, 1),
                                &BIT(wb_plic_xeip, 0)));
    SETVAL(wb_plic_seip, CCx(4, &BIT(wb_plic_xeip, 6),
                                &BIT(wb_plic_xeip, 4),
                                &BIT(wb_plic_xeip, 2),
                                &comb.v_gnd1));

    TEXT();
    SETONE(o_jtag_vref);

    TEXT();
    TEXT("Nullify emty AXI-slots:");
#if GENCFG_XDMA_ENABLE
    SETARRITEM(aximo, glob_bus0_cfg_->CFG_BUS0_XMST_DMA, aximo, amba->axi4_master_out_none);
#endif
    SETVAL(acpo, amba->axi4_master_out_none);

    TEXT();
    TEXT("PRCI:");
    SETVAL(o_prci_apbi, ARRITEM(apbi, glob_bus1_cfg_->CFG_BUS1_PSLV_PRCI, apbi));
    SETARRITEM(apbo, glob_bus1_cfg_->CFG_BUS1_PSLV_PRCI, apbo, i_prci_apbo);
    SETARRITEM(dev_pnp, glob_pnp_cfg_->SOC_PNP_PRCI, dev_pnp, i_prci_pdevcfg);

    TEXT();
    TEXT("DDR:");
    SETVAL(o_ddr_xmapinfo, ARRITEM(bus0_mapinfo, glob_bus0_cfg_->CFG_BUS0_XSLV_DDR, bus0_mapinfo));
    SETARRITEM(dev_pnp, glob_pnp_cfg_->SOC_PNP_DDR_AXI, dev_pnp, i_ddr_xdevcfg);
    SETVAL(o_ddr_pmapinfo, ARRITEM(bus1_mapinfo, glob_bus1_cfg_->CFG_BUS1_PSLV_DDR, bus1_mapinfo));
    SETARRITEM(dev_pnp, glob_pnp_cfg_->SOC_PNP_DDR_APB, dev_pnp, i_ddr_pdevcfg);
    SETVAL(o_ddr_apbi, ARRITEM(apbi, glob_bus1_cfg_->CFG_BUS1_PSLV_DDR, apbi));
    SETARRITEM(apbo, glob_bus1_cfg_->CFG_BUS1_PSLV_DDR, apbo, i_ddr_apbo);
}
