name: CI
on: [push]

jobs:
    linux-gcc:
        name: Linux GCC
        runs-on: ubuntu-22.04
        env:
            CC: gcc-12
            CXX: g++-12
        steps:
            - uses: actions/checkout@v3
            - run: |
                  sudo apt-get update
                  sudo apt-get install -y ninja-build g++-12 libstdc++-12-dev
            - run: /bin/bash .ci/install-vcpkg.sh
            - run: /bin/bash .ci/build-project.sh
            - run: ./build/bin/rivergen

    windows-msvc:
        name: Windows MSVC
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v3
            - run: .ci\install-vcpkg.ps1
            - run: .ci\build-project.ps1
            - run: .\build\bin\Debug\rivergen.exe
            - name: Zip build
              working-directory: ${{ runner.temp }}
              run:  |
                    7z a sv.zip .\build\* -r

            - name: Save build artifact
              uses: actions/upload-artifact@master
              with:
                name: ${{env.ARTIFACT}}
                path: .\${{env.ARTIFACT}}

    mac-gcc:
        name: macOS GCC
        runs-on: macos-latest
        env:
            CC: gcc-12
            CXX: g++-12
        steps:
            - uses: actions/checkout@v3
            - run: brew install gcc@12
            - run: /bin/bash .ci/install-vcpkg.sh
            - run: /bin/bash .ci/build-project.sh
            - run: ./build/bin/rivergen
